MT5_SYMBOL = "XAUUSDm"
MT5_BASE_SYMBOL = "USDZARm"
MT5_PATH = "C:/Program Files/MetaTrader 5 EXNESS/terminal64.exe"
MT5_TIMEFRAME_MINUTES = 15  # Match training timeframe
MT5_COMMENT = "PPO_LSTM"  # Model identifier in MT5
BARS_TO_FETCH = 500  # Match minimum bars needed for feature calculation
LOG_FILE_PATH = f"C:/Users/Admin/Desktop/Logs"
MODEL_PATH = f"C:/Code/drl/bot/model/{MT5_SYMBOL}.zip"
MAX_SPREAD = 35.0  # Maximum allowed spread for trade execution
BALANCE_PER_LOT = 2500.0  # Amount of balance required per 0.01 lot (matches TradingEnv)
STOP_LOSS_PIPS = 2500.0  # Stop loss in pips for all trades
